insert into devices values ('iphone 1', 'phone');
insert into devices values ('iphone 2', 'phone');
insert into devices values ('iphone 3', 'phone');
insert into devices values ('iphone 4', 'phone');
insert into devices values ('iphone 5', 'phone');
insert into devices values ('iphone 6', 'phone');
insert into devices values ('iphone 7', 'phone');
insert into devices values ('iphone 8', 'phone');
insert into devices values ('iphone 9', 'phone');
insert into devices values ('iphone 10', 'phone');
insert into devices values ('asus 1', 'laptop');
insert into devices values ('asus 2', 'laptop');
insert into devices values ('asus 3', 'laptop');
insert into devices values ('asus 4', 'laptop');
insert into devices values ('asus 5', 'laptop');
insert into devices values ('asus 6', 'laptop');
insert into devices values ('asus 7', 'laptop');
insert into devices values ('asus 8', 'laptop');
insert into devices values ('asus 9', 'laptop');
insert into devices values ('asus 10', 'laptop');
insert into devices values ('nvidia shield 1', 'tablet');
insert into devices values ('nvidia shield 2', 'tablet');
insert into devices values ('nvidia shield 3', 'tablet');
insert into devices values ('nvidia shield 4', 'tablet');
insert into devices values ('nvidia shield 5', 'tablet');
insert into devices values ('nvidia shield 6', 'tablet');
insert into devices values ('nvidia shield 7', 'tablet');
insert into devices values ('nvidia shield 8', 'tablet');
insert into devices values ('nvidia shield 9', 'tablet');
insert into devices values ('nvidia shield 10', 'tablet');